apiVersion: v1
kind: PersistentVolume
metadata:
  name: windows-2025-root-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  gcePersistentDisk:
    pdName: windows-2025-root-gce
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-2025-root-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwo
  volumeName: windows-2025-root-pv
