apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-2025-test
  namespace: default
  labels:
    kubevirt.io/vm: windows-2025-test
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-2025-test
    spec:
      domain:
        cpu:
          cores: 4
        memory:
          guest: 16Gi
        devices:
          disks:
          - name: rootdisk
            bootOrder: 2
            disk:
              bus: virtio
          - name: iso-install
            bootOrder: 1
            cdrom:
              bus: sata
          - name: virtiocontainerdisk
            cdrom:
              bus: sata
          gpus:
          - deviceName: "nvidia.com/gpu"
            name: gpu1
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8192
          smm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
      terminationGracePeriodSeconds: 0
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: windows-2025-root-pvc
      - name: iso-install
        dataVolume:
          name: windows-2025-iso
      - name: virtiocontainerdisk
        containerDisk:
          image: quay.io/kubevirt/virtio-container-disk:v1.9.0
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
