#!/usr/bin/env python3
"""
Kayfabe roadmap loop -- driver.

This is a starting-point implementation, not a finished autonomous system.
It deliberately does NOT auto-merge to base_branch and does NOT auto-clear
a phase gate: those are the two points in this codebase where the roadmap
and config.yaml both insist on a human. Everything else (routine
implementation, test iteration, cheap chores) runs unattended within a task.

Usage:
    python main.py run --phase P0                 # work through one phase's tasks
    python main.py gate-report --phase P0          # print the human gate checklist
    python main.py status                          # task graph + ledger summary
"""
from __future__ import annotations
import argparse
import sys
import yaml

from git_ops import GitOps
from model_router import ModelRouter, Task
from token_ledger import TokenLedger
from vertex_client import VertexGeminiClient

MAX_ITERATIONS_PER_TASK = 8  # propose -> apply -> test -> fix, capped so a
                              # genuinely stuck task pauses for a human
                              # instead of burning the budget silently


def load_config(path: str = "config.yaml") -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def load_tasks_for_phase(graph: dict, phase_id: str) -> list[Task]:
    """
    Prefers real tasks (graph['tasks']) filtered to this phase; falls back
    to synthesizing one placeholder Task per model bucket from the planning
    graph if no real tasks have been written yet for this phase. Replace the
    fallback path with real tickets (roadmap.md Section 7) before actually
    running a phase -- the buckets are cost-planning shapes, not real units
    of work a model can execute against.
    """
    real = [t for t in graph.get("tasks", []) if t.get("phase") == phase_id]
    if real:
        return [Task(**t) for t in real]

    phase = next(p for p in graph["phases"] if p["id"] == phase_id)
    print(f"[warn] no real tasks defined for {phase_id} yet -- refusing to run "
          f"placeholder buckets against the model. Create tasks from "
          f"roadmap.md Section 7 and add them under 'tasks:' in task_graph.yaml.",
          file=sys.stderr)
    return []


def run_phase(phase_id: str, cfg: dict, graph: dict):
    tasks = load_tasks_for_phase(graph, phase_id)
    if not tasks:
        sys.exit(1)

    router = ModelRouter(
        cfg["routing"], cfg["routing"]["escalate_after_failures"],
        cfg["human_gate_required_for_paths"],
    )
    git = GitOps(cfg["repo"]["path"], cfg["repo"]["base_branch"], cfg["repo"]["work_branch_prefix"])
    ledger = TokenLedger()
    vertex = VertexGeminiClient(cfg["gcp"]["project_id"], cfg["gcp"]["vertex_region"])

    for task in tasks:
        print(f"\n=== {task.id}: {task.title} ({task.kind}) ===")
        branch = git.start_task_branch(task.phase, task.id)
        print(f"working on {branch}")

        for iteration in range(MAX_ITERATIONS_PER_TASK):
            model_key = router.model_for(task)
            print(f"  iteration {iteration+1}: routing to {model_key}")

            # --- This is the part every real deployment customizes: build a
            # system prompt from repo conventions + relevant file context,
            # send it, and apply the model's proposed patch. Left as a clear
            # extension point rather than a fake implementation. ---
            #
            # result = vertex.call(model_key, system=..., user_content=...)
            # ledger.record(result, task.phase, task.id)
            # apply_patch(result.text, git.repo_path)
            #
            # test_ok = run_tests(task, cfg)
            # if test_ok: break
            # task.failure_count += 1
            raise NotImplementedError(
                "wire up your repo-context builder + patch-apply step here "
                "(see the comment above) -- this is the one part of the loop "
                "that's genuinely repo-specific and shouldn't be templated blindly."
            )

        touched = git.changed_paths()
        task.touches_paths = touched
        if router.requires_human_gate(task):
            print(f"  [HUMAN GATE] {task.id} touches a protected path "
                  f"({touched}); commit is staged on {branch} but NOT merged. "
                  f"Review required before this goes anywhere near base_branch.")
        else:
            git.commit_all(f"[{task.phase}/{task.id}] {task.title}\n\n"
                            f"Generated by kayfabe-loop, model={model_key}, "
                            f"review before merge.")

    print("\n" + ledger.report())
    print(f"\nPhase {phase_id} tasks processed. This does NOT mean the phase "
          f"gate is cleared -- run `python main.py gate-report --phase {phase_id}` "
          f"and check it by hand against roadmap.md's exit criteria.")


def gate_report(phase_id: str, graph: dict):
    phase = next(p for p in graph["phases"] if p["id"] == phase_id)
    print(f"\nPhase {phase_id}: {phase['title']}")
    print(f"Depends on: {phase['depends_on'] or 'none'}")
    print(f"Human gate required: {phase['human_gate']}")
    print(f"\nThis command intentionally does not auto-pass/fail anything.")
    print(f"Copy the 'Exit criteria (Gate {phase_id})' checklist from "
          f"roadmap.md and confirm each box against real, dated, hardware-"
          f"measured evidence -- the loop's own test-green status is necessary "
          f"but not sufficient (see roadmap.md Section 0, point 6).")


def status(graph: dict):
    ledger = TokenLedger()
    print(ledger.report())
    print("\nPhases:")
    for p in graph["phases"]:
        n_real_tasks = len([t for t in graph.get("tasks", []) if t.get("phase") == p["id"]])
        print(f"  {p['id']}: {p['title']} -- {n_real_tasks} real task(s) defined "
              f"(depends_on={p['depends_on']}, human_gate={p['human_gate']})")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_run = sub.add_parser("run")
    p_run.add_argument("--phase", required=True)

    p_gate = sub.add_parser("gate-report")
    p_gate.add_argument("--phase", required=True)

    sub.add_parser("status")

    args = ap.parse_args()
    cfg = load_config()
    with open("task_graph.yaml") as f:
        graph = yaml.safe_load(f)

    if args.cmd == "run":
        run_phase(args.phase, cfg, graph)
    elif args.cmd == "gate-report":
        gate_report(args.phase, graph)
    elif args.cmd == "status":
        status(graph)
